### ISSUE TITLE
Four Years on, how well did this work?

### ISSUE THREAD

**Issue by twinotter** [jayaras/esp8266-nfc-reader#2]
Hi there -

Sorry to use an issue for this. I'm not sure how to send an out-of-band message using GitHub.

So, this project is four years old and your toddler is probably not a toddler anymore. I've got a toddler and am about to build something very close to this. ESP-01 + PN532 to communicate ultimately to a mopidy server running on a pi. MQTT might be a perfect avenue, but I haven't closed the loop with a method to get the message from MQTT to mopidy. I also am depending on it being low power (battery operated) - so that means the ESP8266 deep sleep with 1 second timeout. Or maybe an ESP32 with an IRQ sleep mode.

My intention is to build the circuit into a Leap Frog "Go-With-Me" backpack which already has a nice buck-boost circuit that should suck the marrow out of a couple AAs.

Anyway, before I launch into all that work, how successful was this? Did your kid play with it? Did it go by the wayside quickly? Or do you find they still use it even now?

Thanks!
Rudy

**Comment by jayaras** [comment]
No worries Rudy,
So we actually used this all the way up past preschool and would probably still be using this today if it didn't physically break.   Without the ability to read/write and understand the nuances of modern UI design the sonos is pretty complicated.   Sure I could go and build something with a touchscreen that lets the kids scroll through a list of parent approved songs...  This still works fine and ideally will get a bit of a reboot the next rainy weekend.
